query GetDictionariesData($languageId: Int!) {
	dictionaries(languageId: $languageId) @list(name: "Dictionaries_Page") {
		id
		name
		description
		image
		languageId
		conceptId
		concept {
			id
			path
			depth
			parentId
		}
	}
	languages {
		id
		name
		code
	}
	concepts {
		id
		path
		depth
		parentId
	}
}
