version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_GRAPHQL_ENDPOINT=${VITE_GRAPHQL_ENDPOINT:-http://backend:8000/graphql/}
      - VITE_APP_ENV=${VITE_APP_ENV:-production}
      - VITE_APP_URL=${VITE_APP_URL:-http://localhost:3000}
      - VITE_DEBUG=${VITE_DEBUG:-false}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with hot-reload
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_GRAPHQL_ENDPOINT=${VITE_GRAPHQL_ENDPOINT:-http://localhost:8000/graphql/}
      - VITE_APP_ENV=development
      - VITE_APP_URL=http://localhost:5173
      - VITE_DEBUG=true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge
